#!/usr/bin/env zsh

YQ_VER=4.6.2

YQ_CMD=yq

if ! command -v yq &>/dev/null
then
  if [ ! -f /k/yq ]; then
    echo 'YQ is not found, downloading...'
    curl -L "https://github.com/mikefarah/yq/releases/download/v$YQ_VER/yq_linux_amd64" --output /k/yq -k >/dev/null
    chmod +x /k/yq
  fi

  YQ_CMD=/k/yq
fi
